@startuml "Authenticate User (with Private Key) to hub via ui Process"
|User|


start
:Authentication(UserPuK, UI ID);
floating note left: User meaning User Interface 
|UI|
:Authentication(UserPuK, UI ID);
floating note left: UI meaning Backend
|Hub|
:Authentication(UserPuK, UI ID);

if ( Is UI ID is valid or public access avalibole? ) then (no)
            :return unauthenticated;
            label sp_unauthenticated
            |UI|
            :return unauthenticated;
            |User|
            :return unauthenticated;
            stop
            |Hub|
else(yes)
    if (allowed new registries?) then (no)
        :return unauthenticated;
        |UI|
        :return unauthenticated;
        |User|
        :return unauthenticated;
        stop
        |Hub|
    else (yes)
        |MemDB| 
        :Map session random string to HubPuK str\n (With TTL of 3min);
        |Hub|
    endif

    :return EncryptedJson(UserPuK, \n{HubPuK str,session random string});
    |UI|
    :return EncryptedJson;
endif

|User|
:Decrypt EncryptedJson;

:EncryptedJson(HubPuK, \n{session random string}, signature);
|UI|
:EncryptedJson(HubPuK, \n{session random string}, signature);

|Hub|
:EncryptedJson(HubPuK, \n{session random string}, signature);

if (is signeture valid?) then (no)
    :return unauthenticated;
    |UI|
    :return unauthenticated;
    |User|
    :return unauthenticated;
    stop
    |Hub|
else (yes)
    :EncryptedJson(UserPuK,{session random string, avalible warrooms[] list{id,name}});
endif
|UI|
:EncryptedJson(UserPuK,{session random string, avalible warrooms[] list{id,name}});
|User|
:selected warroom = Select Session WarRoom \nor Try to create new passing parameter (Alias, Name, description);
:Encrypt Json(HubPuK, {session random string, selected warroom});
|UI|
:EncryptedJson;
|Hub|
:Dec EncryptedJson;

if ( decrypted successfuly?\nand signature verified \nand session random string correct ) then (no) 
    :return unauthenticated;
    |UI|
    :return unauthenticated;
    |User|
    :return unauthenticated;
    stop    
    
else (yes)
    |Hub|

    if ( Selected warroom not exists) then (not exists)
        :create new war room;
        :get WarRoomId;
    else (exists)
    endif 

    if (Is allowed to access war room ) then (no) 
        :return un autherized;
        |UI|
        :return un autherized;
        |User|
        :return un autherized;
        stop   
    else (yes)

    endif

    |Hub|
    :new JWT(UserPuKSig,WarRoomId);
    :EncryptedJson(UserPuK, {session, jwt});
    |UI|
    :EncryptedJson(UserPuK, {session, jwt});

endif

|User|
:jwtEnc = EncryptedJson(UserPuK, {session, jwt});
:jwt = DecryptedJson(UserPrK, jwtEnc);
:set JWT as user session;

:send EncryptedJson(HubPuK, { jwt, Command } );
|UI|
:send EncryptedJson(HubPuK, { jwt, Command } );
|Hub|
:Decrypt(HubPrK,EncryptedJson(HubPuK, { jwt, Command } );
if (jwt verified? ) then (no)
    :return unauthenticated;
    |UI|
    :return unauthenticated;
    |User|
    :return unauthenticated;
    stop    

else (yes)
    |Hub|
    :check valid command verify schema;
    :check permissions;
    :result = Execute Command;
    :EncryptedJson(UserPuk, {command,result,jwt});
    |UI|
    :EncryptedJson(UserPuk, {command,result,jwt});
    |User|
    :EncryptedJson(UserPuk, {command,result,jwt});
endif 


end
@enduml